language: php

php:
    - '7.1'
    - '7.2'

install:
    - composer install

script:
    - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
    - php vendor/bin/php-coveralls -v